"""Figures and results/summary.md from results/*.json."""
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from emgdec.data import CLASSES, DAYS

R = Path("results")
FIG = R / "figures"
LABEL = {"reference": "No board (digital 20-450 Hz)", "v2": "v2 (INA333)",
         "v1_envelope": "v1, C9/R15 fitted (envelope)", "v1_raw": "v1, C9/R15 empty (rectified)"}
COLOR = {"reference": "0.4", "v2": "#1f77b4", "v1_envelope": "#d62728", "v1_raw": "#ff7f0e"}
pct = lambda s: f"{100 * s['mean']:.1f} ± {100 * s['sd']:.1f}"


def example_traces(recs_needed=(30, 7)):
    from emgdec.data import FS, load_all
    from emgdec.pipeline import run_chain
    recs = load_all()
    d, c = recs_needed
    sub = {k: v for k, v in recs.items() if k[0] <= 5 or k == (d, c)}
    panels = [(n, {}, LABEL[n] + (", 20 kΩ electrodes" if n.startswith("v1") else "")) for n in LABEL]
    panels.append(("v1_envelope", {"z_electrode": 0.0}, "v1, C9/R15 fitted, if the inputs were buffered"))
    fig, axes = plt.subplots(len(panels), 1, figsize=(8, 8.5), sharex=True)
    for ax, (name, kw, title) in zip(axes, panels):
        sig, _ = run_chain(sub, name, **kw)
        x = sig[(d, c)][: int(1.5 * FS), 0]
        t = np.arange(len(x)) / FS
        ax.plot(t, x, color=COLOR[name], lw=0.6)
        ax.set_ylabel("µV" if name == "reference" else "V at ADC")
        ax.set_title(title, fontsize=9, loc="left")
    axes[-1].set_xlabel(f"s  (day {d}, {CLASSES[c]}, channel 1)")
    fig.tight_layout()
    fig.savefig(FIG / "board_outputs.png", dpi=150)


def main():
    lda = json.loads((R / "lda.json").read_text())
    cnn = json.loads((R / "cnn.json").read_text()) if (R / "cnn.json").exists() else {}
    M, S = lda["main"], lda["sweeps"]
    lines = ["# Results", "",
             "Generated by `make report` from `results/*.json`. Days 5, 7, 63, 68, 110 and 112 are "
             "excluded (byte-identical duplicates, see `results/data_audit.json`). "
             "Balanced accuracy, 11 classes (chance 9.1 %). Mean ± SD across test days. "
             "One subject: these are single-subject numbers.", ""]

    lines += ["## Headline: v1 vs v2, same recordings", "",
              "| Signal chain | Random split (leaky) | Within-day | Cross-day LDA | Cross-day CNN (3 seeds) | Cross-day LDA, 100 mV hum |",
              "|---|---|---|---|---|---|"]
    for name in LABEL:
        m0 = M[f"{name}@0.0"]
        hum = M.get(f"{name}@0.1")
        c = cnn.get(name)
        cnn_cell = (f"{100 * c['test_mean_over_seeds']:.1f} ± {100 * c['test_sd_over_seeds']:.1f}"
                    if c else "not run")
        lines.append(
            f"| {LABEL[name]} | {100 * m0['random_split']['bal_acc']:.1f} | {pct(m0['within_day']['per_day'])} "
            f"| {pct(m0['cross_day']['per_day'])} | {cnn_cell} "
            f"| {pct(hum['cross_day']['per_day']) if hum else 'n/a'} |")
    lines += ["", "CNN column: mean over seeds of the per-day mean, ± SD over seeds.", ""]

    if cnn:
        ctl = json.loads((R / "lda_control.json").read_text()) if (R / "lda_control.json").exists() else {}
        lines += ["## CNN vs LDA on identical training windows", "",
                  "Both trained on days 1-50 (every 4th window), validated on days 51-60, tested on days 61-121.", "",
                  "| Chain | LDA val | LDA test | CNN val | CNN test | CNN + gain aug, test | CNN + polarity aug, test |",
                  "|---|---|---|---|---|---|---|"]
        for name in ("reference", "v2", "v1_envelope", "v1_raw"):
            if name not in cnn:
                continue
            c, l = cnn[name], ctl.get(name)
            val = np.mean([max(r["val_history"]) for r in c["runs"]])
            augs = [cnn.get(f"{name}+{a}") for a in ("gain", "flip")]
            aug = " | ".join(f"{100 * a['test_mean_over_seeds']:.1f} ± {100 * a['test_sd_over_seeds']:.1f}"
                             if a else "-" for a in augs)
            lv = f"{100 * l['val_days_51_60']:.1f}" if l else "-"
            lt = pct(l["test_per_day"]) if l else "-"
            lines.append(f"| {LABEL[name]} | {lv} | {lt} | {100 * val:.1f} "
                         f"| {100 * c['test_mean_over_seeds']:.1f} ± {100 * c['test_sd_over_seeds']:.1f} | {aug} |")
        lines += ["", "CNN: mean over 3 seeds; LDA and CNN test columns are mean over test days.", ""]

    v2 = M["v2@0.0"]
    lines += ["## Same test windows, different training data (v2, LDA)", "",
              "All three score the last 40 % of each of days 61-121.", "",
              f"- 60-day-old model (days 1-60, no recalibration): {pct(v2['recalibration']['old+fresh']['0.0'])}",
              f"- 2 s per class from the same day, nothing else: {pct(v2['recalibration']['fresh']['2.0'])}",
              f"- First 60 % of the same day (~3 s per class): {pct(v2['within_day']['per_day'])} "
              f"(all {len(DAYS)} days, not only test days)", ""]

    lines += ["## What the boards did to the signal", "",
              "| Chain | Pot setting (Ω, ch1-4) | Total gain (ch1-4) | CMRR incl. electrodes (dB) | Samples clipped | Samples above SS14 drop |",
              "|---|---|---|---|---|---|"]
    for name in ("v2", "v1_envelope", "v1_raw"):
        i = M[f"{name}@0.0"]["info"]
        above = f"{100 * i['above_diode_fraction']:.2f} %" if "above_diode_fraction" in i else "n/a"
        lines.append(f"| {LABEL[name]} | {i['pot_ohms']} | {i['total_gain']} | {i['cmrr_db']} "
                     f"| {100 * i['clipped_fraction']:.3f} % | {above} |")

    lines += ["", "## Recalibration (LDA, test = last 40 % of each test day)", "",
              "| Seconds of fresh data per class | " + " | ".join(LABEL[n] + " old+fresh" for n in ("reference", "v2")) +
              " | v2 fresh only |", "|---|---|---|---|"]
    for k in ("0.0", "0.25", "0.5", "1.0", "2.0"):
        row = [pct(M[f"{n}@0.0"]["recalibration"]["old+fresh"][k]) for n in ("reference", "v2")]
        fr = M["v2@0.0"]["recalibration"]["fresh"].get(k)
        lines.append(f"| {k} | " + " | ".join(row) + f" | {pct(fr) if fr else '-'} |")

    lines += ["", "## Reference-recording normalisation (cross-day, classes 1-10)", "",
              "| Chain | Raw features | Normalised by that day's class-0 recording |", "|---|---|---|"]
    for name in LABEL:
        rn = M[f"{name}@0.0"]["reference_normalised"]
        lines.append(f"| {LABEL[name]} | {pct(rn['raw'])} | {pct(rn['normalised'])} |")

    lines += ["", "## Hum sweep (cross-day LDA, 20 kΩ electrodes)", "",
              "| 60 Hz common-mode | " + " | ".join(LABEL[b] for b in ("v2", "v1_envelope", "v1_raw")) + " |",
              "|---|---|---|---|"]
    vcms = (0.0, 0.003, 0.01, 0.03, 0.1, 0.3, 1.0)

    def hum_acc(b, v):
        if v in (0.0, 0.1):
            return M[f"{b}@{v}"]["cross_day"]["per_day"]
        return S[f"{b}@{v}@20000.0"]["cross_day"]

    for v in vcms:
        lines.append(f"| {1000 * v:g} mV | " + " | ".join(pct(hum_acc(b, v)) for b in ("v2", "v1_envelope", "v1_raw")) + " |")

    lines += ["", "## Electrode-impedance sweep (cross-day LDA)", "",
              "| Electrode impedance | " + " | ".join(f"{LABEL[b]}, {h}" for b in ("v2", "v1_envelope", "v1_raw") for h in ("no hum", "100 mV")) + " |",
              "|---|" + "---|" * 6]
    for z in (0.0, 5e3, 10e3, 20e3, 50e3):
        cells = []
        for b in ("v2", "v1_envelope", "v1_raw"):
            for v in (0.0, 0.1):
                s = M[f"{b}@{v}"]["cross_day"]["per_day"] if z == 20e3 else S[f"{b}@{v}@{z}"]["cross_day"]
                cells.append(pct(s))
        lines.append(f"| {'0 (buffered)' if z == 0 else f'{z / 1e3:g} kΩ'} | " + " | ".join(cells) + " |")

    lines += ["", "## Accuracy vs days since training (LDA trained on 5 consecutive days)", "",
              "| Days elapsed | " + " | ".join(LABEL[n] for n in ("reference", "v2")) + " |", "|---|---|---|"]
    for g in M["reference@0.0"]["day_gap"]:
        lines.append(f"| {g} | " + " | ".join(pct(M[f"{n}@0.0"]["day_gap"][g]) for n in ("reference", "v2")) + " |")

    cm = np.array(M["v2@0.0"]["cross_day_confusion"])
    worst = sorted(((cm[i, j], i, j) for i in range(len(cm)) for j in range(len(cm)) if i != j), reverse=True)[:5]
    lines += ["", "## v2 cross-day: most common confusions", ""]
    lines += [f"- {CLASSES[i]} → {CLASSES[j]}: {100 * p:.1f} % of {CLASSES[i]} windows" for p, i, j in worst]
    (R / "summary.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))

    # Figures -----------------------------------------------------------------
    FIG.mkdir(exist_ok=True)
    fig, ax = plt.subplots(figsize=(8, 3.6))
    days = np.array([d for d in DAYS if d > 60])
    for name in LABEL:
        ax.plot(days, M[f"{name}@0.0"]["cross_day"]["series"], color=COLOR[name], label=LABEL[name], lw=1.2)
    ax.axhline(1 / 11, color="k", ls=":", lw=0.8, label="chance")
    ax.set(xlabel="test day (trained on days 1-60)", ylabel="balanced accuracy", ylim=(0, 1))
    ax.legend(fontsize=8, ncol=2)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(FIG / "cross_day.png", dpi=150)

    fig, ax = plt.subplots(figsize=(6, 3.6))
    for b in ("v2", "v1_envelope", "v1_raw"):
        m = [hum_acc(b, v)["mean"] for v in vcms[1:]]
        ax.semilogx([1000 * v for v in vcms[1:]], m, "o-", color=COLOR[b], label=LABEL[b])
    ax.axhline(1 / 11, color="k", ls=":", lw=0.8)
    ax.set(xlabel="60 Hz common-mode on the body, mV", ylabel="cross-day balanced accuracy", ylim=(0, 1))
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3, which="both")
    fig.tight_layout()
    fig.savefig(FIG / "hum_sweep.png", dpi=150)

    fig, ax = plt.subplots(figsize=(6, 3.6))
    ks = [0.0, 0.25, 0.5, 1.0, 2.0]
    for name in ("reference", "v2"):
        rc = M[f"{name}@0.0"]["recalibration"]
        ax.plot(ks, [rc["old+fresh"][str(k)]["mean"] for k in ks], "o-", color=COLOR[name], label=f"{LABEL[name]}, days 1-60 + fresh")
    ax.plot(ks[1:], [M["v2@0.0"]["recalibration"]["fresh"][str(k)]["mean"] for k in ks[1:]], "s--",
            color=COLOR["v2"], label="v2, fresh only")
    ax.set(xlabel="seconds of same-day data per class", ylabel="balanced accuracy", ylim=(0, 1))
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(FIG / "recalibration.png", dpi=150)

    if cnn:
        fig, ax = plt.subplots(figsize=(8, 3.6))
        for name, style in (("reference", "-"), ("v2", "-")):
            ax.plot(days, M[f"{name}@0.0"]["cross_day"]["series"], style, color=COLOR[name], lw=1.2, label=f"LDA, {LABEL[name]}")
            for key, ls, lab in ((name, "--", "CNN"), (name + "+flip", ":", "CNN + polarity aug")):
                if key in cnn:
                    ser = np.mean([r["test_series"] for r in cnn[key]["runs"]], axis=0)
                    ax.plot(days, ser, ls, color=COLOR[name], lw=1.2, label=f"{lab}, {LABEL[name]}")
        ax.set(xlabel="test day (trained on days 1-50/60)", ylabel="balanced accuracy", ylim=(0, 1))
        ax.legend(fontsize=7, ncol=2)
        ax.grid(alpha=0.3)
        fig.tight_layout()
        fig.savefig(FIG / "cnn_vs_lda.png", dpi=150)

    example_traces()


if __name__ == "__main__":
    main()
