// Python and C++ must agree on a recorded trajectory.
// Fixture (generated by python/scripts/make_parity_fixture.py from the headline dataset):
//   parity_config.txt   parameters + initial state + P0
//   parity_sensors.csv  3 s of IMU / encoder / contact samples, walking, contacts changing
//   parity_python.csv   the Python filter's posterior every 10th sample
// The C++ predict() uses a structured F P F^T and the reset only touches the dtheta rows/cols,
// so this also checks those shortcuts against the dense Python reference.
#include <gtest/gtest.h>

#include <cmath>

#include "qeskf/eskf.hpp"
#include "qeskf/io.hpp"

using namespace qeskf;

#ifndef QESKF_TEST_DATA
#error "QESKF_TEST_DATA must point at cpp/tests/data"
#endif

TEST(Parity, CppMatchesPythonOnRecordedTrajectory) {
  const std::string dir = QESKF_TEST_DATA;
  const Config cfg = readConfig(dir + "/parity_config.txt");
  const auto sensors = readCsv(dir + "/parity_sensors.csv");
  const auto expected = readCsv(dir + "/parity_python.csv");
  Eskf f = filterFromConfig(cfg);
  const double dt = scalar(cfg, "dt");
  const int every = static_cast<int>(scalar(cfg, "every"));

  double max_p = 0, max_v = 0, max_q = 0, max_b = 0, max_rel_P = 0;
  size_t e = 0;
  int max_feet = 0;
  for (size_t k = 0; k < sensors.size(); ++k) {
    const SensorRow s = parseRow(sensors[k]);
    const Snapshot snap = f.step(s.acc, s.gyro, s.q, s.c, dt);
    max_feet = std::max(max_feet, snap.nfeet);
    if (k % every != 0) continue;
    ASSERT_LT(e, expected.size());
    const auto& x = expected[e++];
    // columns: k, p(3), v(3), q(4), ba(3), bg(3), Pdiag(15), nfeet
    ASSERT_EQ(static_cast<size_t>(x[0]), k);
    for (int i = 0; i < 3; ++i) {
      max_p = std::max(max_p, std::abs(snap.p(i) - x[1 + i]));
      max_v = std::max(max_v, std::abs(snap.v(i) - x[4 + i]));
      max_b = std::max({max_b, std::abs(snap.ba(i) - x[11 + i]), std::abs(snap.bg(i) - x[14 + i])});
    }
    const Quat qe(x[7], x[8], x[9], x[10]);
    max_q = std::max(max_q, logSO3(quatToRot(qe).transpose() * quatToRot(snap.q)).norm());
    for (int i = 0; i < kNB; ++i)
      max_rel_P = std::max(max_rel_P, std::abs(snap.Pdiag(i) - x[17 + i]) / std::abs(x[17 + i]));
    ASSERT_EQ(snap.nfeet, static_cast<int>(x[32])) << "contact bookkeeping diverged at sample " << k;
  }
  EXPECT_EQ(e, expected.size());
  EXPECT_GE(max_feet, 2);  // the fixture must actually exercise augmentation
  RecordProperty("max_abs_p", std::to_string(max_p));
  std::printf("max |dp| %.3e m, |dv| %.3e m/s, |dtheta| %.3e rad, |db| %.3e, rel dP %.3e\n", max_p, max_v, max_q,
              max_b, max_rel_P);
  EXPECT_LT(max_p, 1e-9);
  EXPECT_LT(max_v, 1e-9);
  EXPECT_LT(max_q, 1e-9);
  EXPECT_LT(max_b, 1e-9);
  EXPECT_LT(max_rel_P, 1e-7);
}
